### ISSUE TITLE
Bulk upload product list

### ISSUE THREAD

**Issue by 5l1v3r1** [otto-de/marketplace-php-sdk#7]
**Is your feature request related to a problem? Please describe.*
I want to use the sdk for bulk upload of products to otto.de which lacks bulk upload option even at its interface.

**Describe the solution you'd like**
Using the sdk to for bulk upload

**Describe alternatives you've considered**
Heuroku or any other platforms could be used for developing 3rd party apps for integration to shopify etc..

**Additional context**
There might be gui based program for easy usage.

**Comment by marcogreiveldinger3798** [comment]
hi @5l1v3r1,

can you elaborate what you exactly mean? 
A bulk upload of products is possible. One request can contain a maximum of 500 product variations.
A quote from the api otto market docs.

> Create or update your product variations and get a process-id to query results. The limit for the number of product variations in one request is 500

With the sdk you could initiate different uploads, each containing e.g. 500 variants. One process per upload is created where you can query the process-status.

A gui is available via browser through the [otto partner connect portal (OPC) ](https://portal.otto.market/).

**Comment by marcogreiveldinger3798** [comment]
Closed due inactivity.
Feel free to reopen any time.
